### PR TITLE
Fix windows compatibility

### PR DESCRIPTION
**Pull request by mintchkin**
For some reason, the python binaries directory is named `Scripts` on windows instead of `bin`. Everything seems to work as-is otherwise.

### CODE REVIEW

**Comment by mattsb42** [comment]
### AWS CodeBuild CI Report

* Result: SUCCEEDED
* [Build Logs](https://dp2i705buh.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b326e525-f91c-4323-b070-61a9ef6cee3f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mattsb42** [comment]
### AWS CodeBuild CI Report

* Result: SUCCEEDED
* [Build Logs](https://dp2i705buh.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4087a31b-c2d6-4c37-a754-37b932090e77%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mattsb42** [comment]
### AWS CodeBuild CI Report

* Result: SUCCEEDED
* [Build Logs](https://dp2i705buh.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=fbc533bc-5c94-4b56-a13f-5be56f3de02a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mattsb42** [comment]
This is published now in v1.0.1 (and we have Windows CI now!)

**Comment by mintchkin** [comment]
Awesome, thanks a lot for this project! 👏

**Pull request merged**
